### ISSUE TITLE
Bring back the configPath (custom path to nightwatch.json config file)

### ISSUE THREAD

**Issue by tortila** [gextech/grunt-nightwatch#30]
Right now there's no way to run nightwatch with custom nightwatch.json config file. I'd like to have an option of storing the nightwatch.json file outside of node modules and be able to provide a path to that file for grunt task. 

This option was available some time ago.

**Comment by pateketrueke** [comment]
By now `grunt-nightwatch` tries for a `nightwatch.json` file in the current-working-directory, so it would happen automatically.

If not, you can workaround this with:

```coffee
module.exports = (grunt) ->
  grunt.initConfig
    nightwatch:
      options:
        grunt.file.readJSON grunt.cli.options.json

  grunt.loadNpmTasks 'grunt-nightwatch'
``` 

**example.json**

```json
{
  "standalone": true
}
``` 

Usage: `grunt nightwatch --json example.json`.

This way you can import all required settings and `grunt-nightwatch` will handle the rest.

I'll work out on that, so much thanks for your advice.
