### ISSUE TITLE
Setting custom destination path for downloading selenium standalone jar file

### ISSUE THREAD

**Issue by tortila** [gextech/grunt-nightwatch#31]
I want to be able to store selenium jar file outside of node modules and set a path for it in grunt task options. So if the standalone boolean is set to true, the scenario would be:
* check for the jar_path

    -> if path is set, check if jar file is already there
        ----> if jar is not there, download the jar using jar_url into jar_path directory

    -> else if path is not set, use default path and check if jar file is already there
        ----> if jar is not there, download the jar into default path

**Comment by pateketrueke** [comment]
I got it, I'll work on that feature, thanks for your feedback.
