### ISSUE TITLE
Webdriver for chrome won't start 

### ISSUE THREAD

**Issue by tortila** [gextech/grunt-nightwatch#39]
So I have a path for chrome webdriver inside of custom config file, and it's resolved properly (I can see the correct path with verbose mode of execution). The binary is OK, because I checked it also with running nightwatch globally (using the same config file) - everything works just fine. 
And when I run grunt task for nightwatch and `"chrome"` specified as `browserName` in `default` envifonment settings (under `desiredCapabilities`) I get the following output:

````javascript
[Example] Test Suite
========================

Running:  Should display something 

INFO Request: POST /wd/hub/session 
 - data:  {"desiredCapabilities":{"browserName":"chrome","javascriptEnabled":true,
"acceptSslCerts":true,"platform":"ANY","name":"Example"}} 
 - headers:  {"Content-Type":"application/json; charset=utf-8","Content-Length":133}
ERROR Response 500 POST /wd/hub/session{ sessionId: null,
  status: 13,
  state: 'unhandled error',
  value: 
   { message: 'The path to the driver executable must be set by the webdriver.chrome.driver 
system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. 
The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html',
     suppressed: [],
     localizedMessage: 'The path to the driver executable must be set by the webdriver.chrome.driver 
system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. 
The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html',
     cause: null,
     class: 'java.lang.IllegalStateException',
     hCode: 1525379081,
     screen: null },
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1642283609 }
>> 
>> Connection refused! Is selenium server started?
>> 
Warning: Task "nightwatch" failed. Use --force to continue.

Aborted due to warnings.

````

"Connection refused" message might be tricky, because Selenium is started (I checked).

**Comment by pateketrueke** [comment]
Interesting, the same happens to me.

I also ran the `selenium-server-standalone-2.44.0.jar` specifying the chrome-driver manually, and then use `grunt-nightwatch` in non-standalone mode: works as expected (?)

But of course, standalone mode doesn't work anymore.

Another interesting detail:

```
INFO Request: POST /wd/hub/session
...
```

I'm not sure if that message comes from selenium process (?), so...

> "Connection refused" message might be tricky, because Selenium is started (I checked).

Totally agree. I actually have not idea what's happening.

It could be a nightwatch's specific issue but i'm not sure without reasoning about.
