### ISSUE TITLE
Problem with targets

### ISSUE THREAD

**Issue by jpablo** [gextech/grunt-nightwatch#49]
Hi, I'm struggling defining targets that override the default options attribute:

```javascript
nightwatch: {
            options: {
               globals: { x: 1 }
            },
            a: {
                options: {
                    globals: {x:2}
                }
            }
}
```

I.e., running `grunt nightwatch:a` doesn't seem to have any effect. I still get `browser.globals.x === 1`.

Is this a known limitation?

**Comment by pateketrueke** [comment]
Actually the current merge strategy is not well defined to cover all cases.

However I think you can use the following:
```javascript
nightwatch: {
  options: {
    globals: { x: 1 }
  },
  a: {
    globals: { x: 2 }
  }
}
```

Let me know if that works for you.

**Comment by jpablo** [comment]
It worked, thanks!

**Comment by jpablo** [comment]
Well, it kind of works. If I don't put the key in `nightwatch.options.globals` then it gets used with `grunt nightwatch:a`. At least I can have multiple tasks, albeit no default one.
```
nightwatch: {
  options: {
    globals: {  }
  },
  a: {
    globals: { x: 2 }
  }
}
```
