### ISSUE TITLE
Update nightwatch.js dependency to newer version

### ISSUE THREAD

**Issue by rocketsue** [gextech/grunt-nightwatch#50]
Please update the nightwatch dependency to a more recent version.
Current version in package.json: 0.6.1
Most recent nightwatch.js version: 0.7.2

**Comment by redaxmedia** [comment]
Vote+

**Comment by pateketrueke** [comment]
Sorry for the lag, now `0.4.7` (`nightwatch@0.7.4`) is published. :beers:

**Comment by redaxmedia** [comment]
Great! Thank you

**Comment by rocketsue** [comment]
Yay :) thanks!
