### ISSUE TITLE
Cannot set property 'argv' of undefined

### ISSUE THREAD

**Issue by hayesmaker** [gextech/grunt-nightwatch#56]
Does anyone know how to fix this error:

```
grunt nightwatch
Running "nightwatch" task
Warning: Cannot set property 'argv' of undefined Use --force to continue.
```

It happened after i tried to use the built in nightwatch grunt task instead of this one.. but couldn't get that one working either, so returned to this one... but i removed all the previous task setup for the built in nightwatch grunt in my gruntfile.js.

  

```
    grunt.loadNpmTasks('grunt-nightwatch');
    // E2E Tests
    nightwatch: {
      default: {
        standalone: true,
        config_path: './test/e2e/nightwatch/nightwatch.json'
      },
      // grunt nightwawch:browserstack currently isn't working via Grunt..
      // follow instructions in test/e2e/nightwatch/README.md: # Run Tests in browsertack
      browserstack: {
        standalone: true,
        config_path: './test/e2e/nightwatch/browserstack.json'
      }
    }
```

**Comment by pateketrueke** [comment]
Rename the default key to options, or just add an empty options property; tell me if that works for you. Anyway it's a bug, I'll fix it asap.
