### ISSUE TITLE
Can't pass `argv` to options in grunt because you override it

### ISSUE THREAD

**Issue by hackhat** [gextech/grunt-nightwatch#59]
https://github.com/gextech/grunt-nightwatch/blob/master/tasks/nightwatch.js#L21 you are overriding the argv with `grunt.cli.options`. Can you please let us define in the grunt config?

Also consider changing the readme where you state `Currently, grunt-nightwatch supports the same options as nwrun can handle.` because is not true. (nwrun handles argv, target)

**Comment by pateketrueke** [comment]
I've been working on this, now you can specify both options:

```js
grunt.initConfig({
  nightwatch: {
    options: {
      argv: {},
      target: []
    }
  }
});
```

Release: `0.5.3`
