### ISSUE TITLE
Not all supported arguments are passed to nightwatch

### ISSUE THREAD

**Issue by ap0calypt1c** [gextech/grunt-nightwatch#61]
When doing configuration in the grunt file not all arguments put there are passed to the nightwatch runner. Currently it only takes 'tag', 'test', 'filter', 'verbose', 'group', 'skipgroup' and discard the others. What about retries, suiteRetries and any other that is supported? Can we have at least these two?

**Comment by pateketrueke** [comment]
Sure, I need to update then `nwrun` to take into account newer options.

Thanks for your feedback!

**Comment by ap0calypt1c** [comment]
I can create pull request tonight so you can just approve it and we have it done. Would this work for you?

**Comment by pateketrueke** [comment]
Sure!
