### ISSUE TITLE
Redundant nightwatch installation

### ISSUE THREAD

**Issue by davidlinse** [gextech/grunt-nightwatch#63]
As far as i can see/tell one needs to have _NightwatchJS_ installed as local module.

When running `$ npm list` you'll get 

```sh
├─┬ grunt-nightwatch@0.5.3
│ └─┬ nwrun@0.1.1
│   └─┬ nightwatch@0.8.18       <-- nightwatch is already present in project
│     ├─┬ chai-nightwatch@0.1.1
│     │ ├── assertion-error@1.0.0
```

But having _NightwatchJS_ installed _globally_ or not at all will result in a error like:
`'Can not find module "nightwatch" error.'` 

You'll need to run `$ npm install nightwatch` inside you project to get rid of this error.
Is this the intended behaviour ?

Best regards
~david

**Comment by pateketrueke** [comment]
Actually that was totally intended, but recently I'm fan of discover-and-require techniques for loading modules from local, parent or global installations. That approach allows us to put the required dependency wherever we like to... let me update `nwrun` to do the same so, thanks for your feedback!

**Comment by pateketrueke** [comment]
Not sure if solved but I've release a `nwrun` patch for that, could you `npm update` ?

**Comment by davidlinse** [comment]
Hi.. I've triggered an `npm update` with no change.. I've reinstalled _grunt-nightwatch_ and the included dependency is gone.. 

```
├─┬ grunt-nightwatch@0.5.3
│ └─┬ nwrun@0.2.0
│   └── deduct@0.0.1
```

It works with _Nightwatch_ as _"local" dependency but still fails with _Nightwatch_ installed globally.

regards
~david

**Comment by pateketrueke** [comment]
Which version of node/npm you're using?

Can you share the output of the following command?

```bash
$ npm root -g
```

**Comment by davidlinse** [comment]
Sure.. 
```
$ npm root -g
  info - it worked if it ends with ok
  info - using yapm@2.4.2
  info - using node@v0.10.28
/usr/local/lib/node_modules
  info - ok
```

regards
~david

**Comment by pateketrueke** [comment]
Seems like you're running non-standard NPM and an older version of NodeJS... I'm not sure if everything will work in your system because `deduce` relies on `execSync` and isn't supported for your version...

If you can test the following snippet would be great:

```js
console.log(require('child_process').execSync('npm root -g').toString());
```

**Comment by pateketrueke** [comment]
Update: another solution would be using `npm link nightwatch` inside your project, that way you link the global dependency locally.

**Comment by pateketrueke** [comment]
I'm closing this since `npm link` is a good solution.
