### ISSUE TITLE
Grunt cannot find module 'nightwatch'

### ISSUE THREAD

**Issue by alex7egli** [gextech/grunt-nightwatch#67]
I'm on windows 10 using grunt-nightwatch v0.5.4, grunt-cli v1.2.0, and npm v2.15.9. I ran npm install grunt-nightwatch --save, and I can see grunt-nightwatch in my node_modules. I then added the nightwatch task to my gruntfile like this:

```
grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        nightwatch: {
            options: {
            }
        }
});
grunt.loadNpmTasks("grunt-nightwatch");
```

When I run: grunt nightwatch I get the error:
Loading "nightwatch.js" tasks...ERROR
>> Error: cannot find module 'nightwatch'
Warning: Task "nightwatch" not found. Use --force to continue.

Is there an npm module called 'nightwatch' that's required to run this? I have nightwatch installed globally, but not locally and have been running tests with it fine for a long time just using the 'nightwatch' command.

**Comment by pateketrueke** [comment]
> Is there an npm module called 'nightwatch' that's required to run this?

Yes, `grunt-nightwatch` is only a wrapper around Nightwatch itself, please install locally nightwatch within your project.

**Comment by alex7egli** [comment]
I installed it locally and it worked. I thought my global installation would be used by default but I guess not. How come nightwatch is only a devDependency and not a dependency in the grunt-nightwatch module?
